export const ADD_BANK_INFORMATION = 'ADD_BANK_INFORMATION'

export const GET_ALL_BANK_INFORMATION = 'GET_ALL_BANK_INFORMATIION'
export const GET_ALL_BANK_INFORMATION_SUCCESS = 'GET_ALL_BANK_INFORMATIION_SUCCESS'


export const DELETE_BANK_INFORMATION = 'DELETE_BANK_INFORMATION'

export const UPDATE_BANKINFORMATION = 'UPDATE_BANKINFROMATION'
export const ADDED_BANKINFORMATION_SUCCESS = "ADDED_BANKINFORMATION_SUCCESS"
export const ADDED_BANKINFORMATION_FAIL = "ADDED_BANKINFORMATION_FAIL"
