export const ADD_REVERSE_VOUCHER_ENTRY = "ADD_REVERSE_VOUCHER_ENTRY";
export const ADD_REVERSE_VOUCHER_ENTRY_SUCCESS = "ADD_REVERSE_VOUCHER_ENTRY_SUCCESS";
export const ADD_REVERSE_VOUCHER_ENTRY_FAIL = "ADD_REVERSE_VOUCHER_ENTRY_FAIL";

export const ADD_UNPOST_VOUCHER_ENTRY = "ADD_UNPOST_VOUCHER_ENTRY";
export const ADD_UNPOST_VOUCHER_ENTRY_SUCCESS = "ADD_UNPOST_VOUCHER_ENTRY_SUCCESS";
export const ADD_UNPOST_VOUCHER_ENTRY_FAIL = "ADD_UNPOST_VOUCHER_ENTRY_FAIL";