export const ADD_BRANCH_INFORMATION = 'ADD_BRANCH_INFORMATION'
export const GET_BRANCH_INFORMATION = 'GET_BRANCH_INFORMATION'

export const GET_ALL_BRANCH_INFORMATIION_SUCCESS = 'GET_ALL_BRANCH_INFORMATIION_SUCCESS'

export const ADDED_BRANCHINFORMATION_SUCCESS = "ADDED_BRANCHINFORMATION_SUCCESS"
export const ADDED_BRANCHINFORMATION_FAIL = "ADDED_BRANCHINFORMATION_FAIL"
export const UPDATE_BRANCHINFORMATION = 'UPDATE_BRANCHINFROMATION'
