export const COA_ANALYSIS_IMPORT = "COA_ANALYSIS_IMPORT";
export const COA_ANALYSIS_IMPORT_SUCCESS = "COA_ANALYSIS_IMPORT_SUCCESS";
export const COA_ANALYSIS_IMPORT_FAILURE = "COA_ANALYSIS_IMPORT_FAILURE";


export const COA_IMPORT_BY_ID_DATA = "COA_IMPORT_BY_ID_DATA";
export const COA_IMPORT_BY_ID_DATA_SUCCESS = "COA_IMPORT_BY_ID_DATA_SUCCESS";
export const COA_IMPORT_BY_ID_DATA_FAILURE = "COA_IMPORT_BY_ID_DATA_FAILURE";