export const ADD_REVISE_VOUCHER_UPLOAD = 'ADD_REVISE_VOUCHER_UPLOAD';
export const ADD_REVISE_VOUCHER_UPLOAD_SUCCESS = 'ADD_REVISE_VOUCHER_UPLOAD_SUCCESS';
export const ADD_REVISE_VOUCHER_UPLOAD_FAIL = 'ADD_REVISE_VOUCHER_UPLOAD_FAIL';