export const ADD_REVISE_VOUCHER_ENTRY = "ADD_REVISE_VOUCHER_ENTRY";
export const ADD_REVISE_VOUCHER_ENTRY_SUCCESS = "ADD_REVISE_VOUCHER_ENTRY_SUCCESS";
export const ADD_REVISE_VOUCHER_ENTRY_FAIL = "ADD_REVISE_VOUCHER_ENTRY_FAIL";