export const ADD_VOUCHER_ENTRY_FORM = 'ADD_VOUCHER_ENTRY_FORM'
export const ADD_VOUCHER_ENTRY_SUCCESS = "ADD_VOUCHER_ENTRY_SUCCESS"
export const ADD_VOUCHER_ENTRY_FAIL = "ADD_VOUCHER_ENTRY_FAIL"


export const GET_SAVED_VOUCHER_LIST = "GET_SAVED_VOUCHER_LIST"

export const GET_VOUCHER_BY_ID = "GET_VOUCHER_BY_ID"
export const GET_VOUCHER_BY_ID_SUCCESS = "GET_VOUCHER_BY_ID_SUCCESS"
export const GET_VOUCHER_BY_ID_FAIL = "GET_VOUCHER_BY_ID_FAIL"

export const POST_VOUCHER_ENTRY = "POST_VOUCHER_ENTRY"
export const DELETE_VOUCHER_ENTRY = "DELETE_VOUCHER_ENTRY"


export const REVIEW_VOUCHER = "REVIEW_VOUCHER"
