export const GET_VOUCHER_CHANGES_BY_REF_REQUEST = "GET_VOUCHER_CHANGES_BY_REF_REQUEST";
export const GET_VOUCHER_CHANGES_BY_REF_SUCCESS = "GET_VOUCHER_CHANGES_BY_REF_SUCCESS";
export const GET_VOUCHER_CHANGES_BY_REF_FAIL = "GET_VOUCHER_CHANGES_BY_REF_FAIL";
